### ISSUE TITLE
iinfino support for vLLM

### ISSUE THREAD

**Issue by eswarthammana** [infinohq/infino#146]
Hi, 

currently i am exploring [ vLLMOpenAI ](https://python.langchain.com/docs/integrations/llms/vllm#openai-compatible-completion) with Llama2 using Lang chain.

i would like to know shall i use infino for vLLMOpenAI
currently i could see empty response, /ping gives ok (so the infino server is working)

and also default base_url currently is https://localhost:3000, please update to http://localhost:3000

**Comment by vinaykakade** [comment]
Will explore the support for vLLMOpenAI. If you'd like to help (the changes would likely be in LangChain repo) - let us know.

Thanks for reporting the based URL issue - fixed and new client is pushed - https://pypi.org/project/infinopy/

**Comment by eswarthammana** [comment]
Thanks for the update @vinaykakade 

Post updating the URL status to http, SSL issues got resolved, but neither the docker image nor build from the source is not successfully due to changes at the RabbitMQ source.

predicates v3.0.4 requires rustc 1.69 or above
anstyle v1.0.4 requires rustc 1.70 or above

After updating the Rust to 1.70 working fine.

please find an alternative to avoid this conflicts, 
may by maintain a RabbitMQ build during the new build rather always fetch from the remote example... RabbitMQ binary in the infino code.
