### ISSUE TITLE
Update infino-opensearch-plugin to build for OpenSearch 2.x

### ISSUE THREAD

**Issue by santhoshsram** [infinohq/infino#185]
# Context
OpenSearch (OS) stable version is 2.11.1. OS 3.0.0 is not planned for at least a quarter. 3.0.0 is the version of github OS main branch and our plugin is set to build for OS 3.0.0 (by default). Presuming most / all customers would want to run a stable OS version, I am trying to build and run the plugin with OS 2.x (2.11.1 specifically) so that we can test with this combo.

# tl;dr
There are breaking changes from OS 2.x to 3.x that is preventing the infino plugin builds for OS 2.x. Need help to fix this and proceed further. I think it’s important for us to have a plugin that works with one of the OS 2.x stable releases.

# Problem
- installing infino-opensearch-plugin-3.0.0 in OS 2.11.0 (running in docker) fails due to version mismatch
- building plugin for OS 2.11.1 using `./gradlew build -Dopensearch.version=2.11.1` results in a compile time error. Reason:
  - test InfinoPluginIT uses packages `org.apache.hc.core5.http.ParseException` and `import org.apache.hc.core5.http.io.entity.EntityUtils` from `httpclient5` (org.apache.httpcomponents.client5:httpclient5:5.3). The switch from httpclient to httpclient5 happened in OS 3.x. OS 2.x is setup to build and run with httpclient.
- Adding `org.apache.httpcomponents.client5:httpclient5:5.3` as a dependency in build.gradle doesn’t work for me. _Likely I’m not doing it right._

# Analysis
- OS version bump to 3.x happened in 2022 and all plugins that use httpclient have switched to using httpclient5 around the same time.
- Other plugins (like k-nn) that use httpclient5 don’t have this problem and can be build for any version of OS, as their code is moving in lockstep with OS core.
- We have this challenge as we started building off of 3.x and we use packages not available (by default) with OS 2.x.

# Possible solutions
## Option 1
- On a separate branch update plugin code to use httpclient  instead of httpclient5 (also repeat same for other package dependencies) and get it to build for OS 2.x.
- Tag this change as 2.11.1 (and a few other 2.x verions) so that we can easily identify the git commit to build for OS 2.x.
  - Sidenote: OS seems to be using a similar technique for tagging different releases.
- Revert to using httpclient5 on the main branch so that the version on plugins main branch matches that on OS’s main branch.
- When we update the plugin with new code we’ll have to make sure it is compatible with both 2.x and 3.x, until 3.x become the stable release

## Option 2
- Figure out how to correctly insert httpclient5 (and other such packages we run into in the future) as a dependency for the plugin so that we can build for OS 2.x or 3.x from the plugin’s main branch

# Workaround
For now, I’ll continue testing the plugin with OS 3.0.0 (main branch) that I build locally. I can also build a few docker images and push them to dockerhub so that any of us can run the tests. But we should get the plugin working 2.x if we target early customers to try Inifno.

**Comment by ekechinwokah** [comment]
Submitted PR: https://github.com/infinohq/infino/pull/186

**Comment by ekechinwokah** [comment]
To address this (at least to build from 2.11.1 to v2.6.0)

- Changed to standard HTTPlib
- Modified Mockito dependencies to track with OpenSearch (e.g. Mockito 5.5.0 => OpenSearch 2.11.0, etc.)
- Used reflection to conditionally load appropriate import classes for different OpenSearch versions (the fact that the import path changed for the same classes is particularly onerous to handle)
- Switched from ActionListener to (deprecated) AcknowledgedResponse when creating/deleting Lucene indexes for now
