### ISSUE TITLE
Benchmark improvements

### ISSUE THREAD

**Issue by vinaykakade** [infinohq/infino#2]
1. Benchmark for logs across infino/elasticsearch/quickwit and tsldb/lucene/tantivy.
2. Benchmark for time series across infino/prometheus.
3. Benchmark disk usage, memory usage, insertion speed, and search speed across at least 3 datasets.

**Comment by savannahar68** [comment]
At the granular level - Benchmark for logs and time-series should have 

1. Insertion benchmark
2. Search benchmark
3. Size benchmark

**Comment by savannahar68** [comment]
Picking up point 1

**Comment by savannahar68** [comment]
Picking up 2 - Benchmark for time series across infino/prometheus this week

**Comment by vinaykakade** [comment]
1 and 2 are fixed. No plan for 3 as the higher level benchmark is sufficient for now.
