### ISSUE TITLE
Search operation performance improvements

### ISSUE THREAD

**Issue by savannahar68** [infinohq/infino#20]
Instead of iterating over each segment one by one, parallelly search the query in multiple segments.

We can use this https://docs.rs/rayon/latest/rayon/ to search concurrently.

Along with this PR, one should benchmark the optimal parameters for concurrency.

**Comment by savannahar68** [comment]
Using skip pointers as optimisation when query has multiple words

**Comment by vinaykakade** [comment]
Fixed #82
