### ISSUE TITLE
Creating a new index at random location with tsldb crashes app

### ISSUE THREAD

**Issue by savannahar68** [infinohq/infino#22]
With introduction of settings, we are expecting the index dir path to have default.toml file

`let result = Settings::new(config_dir_path);`

The behaviour ACC to me should be 
1. If path doesn't have default settings file, then copy from known location
2. If it has continue

**Comment by savannahar68** [comment]
@vinaykakade wdyt

**Comment by vinaykakade** [comment]
Thanks for reporting. I would suggest giving an error if the path doesn't have a settings file. And we'll be providing a default with our distribution (in the 'config' directory).

The main reason is it is a way to educate the user that settings are required, and what they should be.

**Comment by savannahar68** [comment]
@vinaykakade 
Need to pick it up. I can close this by tonight. If we are in blocked because of this and need it urgently you can take it.

**Comment by savannahar68** [comment]
As we discussed, the user of the library should provide a path of dir where config is already present.
Given this is already present, closing this issue.
