### ISSUE TITLE
Tests fail when infino server is running

### ISSUE THREAD

**Issue by vinaykakade** [infinohq/infino#30]
### Description

When infino server is running, tests fail due to a port conflict while starting rabbitmq.

### Steps to Reproduce

1. Start infino server
2. Run `cargo test -- --ignored`

**Expected behavior:**

Tests should pass.

**Actual behavior:**

Tests fail due to a port conflict in rabbitmq.

**Reproduces how often:**

Every time.

### Additional Information

Need to make sure the tests use a different rabbitmq port than the server.

**Comment by naman-modi** [comment]
Even, I was facing the same issue yesterday. 
@vinaykakade, In this issue, I think we should also make all the tests mandatory.

**Comment by vinaykakade** [comment]
Fixed in #34
