### ISSUE TITLE
loom-tests: failing with error: no function or associated item named `new_with_max_params`

### ISSUE THREAD

**Issue by naman-modi** [infinohq/infino#31]
### Description

error[E0599]: no function or associated item named `new_with_max_params` found for struct `Tsldb` in the current scope. With the change to include configuration, the method `new_with_max_params` was removed and changes were made to load from configuration, but the loom tests were not updated.

### Steps to Reproduce

1. Run loom tests.

**Expected behavior:**

Tests should pass.

**Actual behavior:**

Tests are failing with `error[E0599]: no function or associated item named `new_with_max_params` found for struct `Tsldb` in the current scope.`

### Additional Information

- NA

**Comment by vinaykakade** [comment]
Fixed in PR #28
