### ISSUE TITLE
GH Workflows

### ISSUE THREAD

**Issue by naman-modi** [infinohq/infino#39]
## Summary
Leverage GH workflows to:
- Run test when PR is raised.
- Run CI when pushed to main

## Motivation
To make sure any build of `main` is error free, and expected functionalities work well.

## Additional context
N.A.

**Comment by vinaykakade** [comment]
@naman-modi - can this be closed or is there any remaining work here?

**Comment by naman-modi** [comment]
The initial setup is up and working, so we can close. Further subtasks to be done, can be created as separate issues when required, @vinaykakade.
