### ISSUE TITLE
How to run infino in windows

### ISSUE THREAD

**Issue by eswarthammana** [infinohq/infino#86]
I am exploring langchain, as part of logging and usage stats, i was redirected to infino. But it seems i need to have docker to run the application.

I have no access to docker, could you please help me to run this application in windows as a service or application.
Please share your suggestions or steps.

**Comment by vinaykakade** [comment]
You can run Infino directly without docker - in case you don't have access to docker. Please follow the following steps:

1. Install the rust toolchain - https://www.rust-lang.org/tools/install
2. Clone the Infino repo
3. From the directory you have cloned the repo in, run `make run`. This will start the Infino server by default on port 3000. 

Once the server is started, you can use LangChain-Infino integration to send logging and usage stats to Infino. 
* LangChain documentation - https://python.langchain.com/docs/integrations/providers/infino
* Example notebook - https://github.com/infinohq/infino/blob/main/examples/llm-monitoring-langchain/llm-monitoring-langchain.ipynb (no need to start Infino server using docker as shown in this example, if you have it running already following the above steps).

**Comment by eswarthammana** [comment]
Hi @vinaykakade 

Thanks for the detailed steps.

> To Run rust in windows we need Windows Build tools, which downloaded and installed.
> To run the make file i have downloaded the Chocolatey then installed make.

While run the command make run under the repo, i have faced the following issue mentioned in the attachment. Please share your thoughts and suggestions.

![error](https://github.com/infinohq/infino/assets/23114153/1fad1b05-e946-437c-abeb-f6a9e7f3a544)

**Comment by vinaykakade** [comment]
Thanks. I am trying to get access to a Windows native host to reproduce this.

In the meantime, is using WSL2 (https://learn.microsoft.com/en-us/windows/wsl/install) an option at all? In that case, you'll be in the standard Linux environment, using a Windows machine.

**Comment by eswarthammana** [comment]
No @vinaykakade , needs a lot of approvals

**Comment by vinaykakade** [comment]
Thanks @eswarthammana. This [commit](https://github.com/infinohq/infino/commit/f0079cb3b6d47d947f0d9931c7006f6e54df9d0e) should fix the issue. I am now able to start the server on Windows. Pl let me know in case you are still running into any issue.

**Comment by eswarthammana** [comment]
Able to start the infino server.

The example mentioned [in langchain](https://github.com/infinohq/infino/blob/main/examples/llm-monitoring-langchain/llm-monitoring-langchain.ipynb) works fine!. However, with ChatOpenAI, we are not able to see any of the mentioned graph data.

sample part of the code shown below.
```
client = InfinoClient()
handler = InfinoCallbackHandler(model_id="test_openai", model_version="0.1", verbose=False)
llm = ChatOpenAI(temperature=0)
map_chain = LLMChain(llm=llm, prompt=map_prompt, calssbacks=[handler])
```

**Comment by vinaykakade** [comment]
Thanks @eswarthammana. Can you please open a new issue for supporting ChatOpenAI? That way, we can track it better.

Will get to adding support for the same shortly.

**Comment by eswarthammana** [comment]
https://github.com/infinohq/infino/issues/93
